version: '3.7'

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: app
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default:
